dozer:
    configuration:
        classpath:config/dozer/mapping.xml


spring:
    jpa:
        openInView: false
        generate-ddl: false
        hibernate:
            ddl-auto:
                none

        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
