dozer:
    configuration:
        classpath:config/dozer/mapping.xml


spring:
    jpa:
        hibernate:
            ddl-auto:
                none
            format_sql:
                true
